# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TetrominoTouchKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TetrominoTouchKit
  pod 'TetrominoKit', :git => 'https://github.com/Stitch7/Tetromino/tree/Cocoapods/TetrominoKit'
  #, :branch => '' 

  pod 'LTMorphingLabel'

  target 'TetrominoTouchKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
